import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync,rmSync,readFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{zipSync,unzipSync,strToU8,strFromU8}from'fflate';import sharp from'sharp';import{Store}from'../server/store.ts';import{Intake,hash}from'../server/intake.ts';import{Evidence}from'../server/evidence.ts';import{Backups,BACKUP_TABLES}from'../server/backup.ts';import{blankRide,summarize}from'../src/shared/domain.ts';
const complete=()=>({...blankRide(),trip_date:'2026-10-06',pickup_time:'09:30:00',financial_basis:'worksheet_cash_plus_credit' as const,cash_collected_paisa:50000,uber_credit_paisa:0,tips_paisa:4000,commission_paisa:5000,pass_charge_paisa:0,financial_confirmed:true});
function altered(archive:Buffer,mutate:(data:any,files:Record<string,Uint8Array>)=>void){const files=unzipSync(archive);const data=JSON.parse(strFromU8(files['data.json']!));mutate(data,files);files['data.json']=strToU8(JSON.stringify(data));return Buffer.from(zipSync(files));}
test('M4 complete snapshot/restore round trip, staged validation and activation failure recovery',async()=>{
 const root=mkdtempSync(join(tmpdir(),'uber-backup-')),fresh=mkdtempSync(join(tmpdir(),'uber-fresh-'));let store=new Store(root);let destination=new Store(fresh);
 try{
  const intake=new Intake(store),evidence=new Evidence(store,intake);store.afterSave=r=>evidence.finalize(r);
  const image=await sharp({create:{width:70,height:50,channels:3,background:'white'}}).png().toBuffer();const batch=intake.batches([{name:'private-source.png',size:image.length,type:'image/png'}]);const uploaded=await intake.upload(batch.id,0,image);const item=uploaded.group!.items[0]!;const job=intake.job(item.id,'start')as{token:string};intake.job(item.id,'complete',job.token,{text:'Cash collected: BDT 500.00',confidence:95,blocks:[],tsv:''});
  const draft=intake.draft(uploaded.group!.id);const reviewed=store.save(complete(),'reviewed',draft.id,1);store.save(blankRide(),'draft');const trash=store.save(blankRide(),'draft');store.change(trash.id,'trash',1);
  const sid=crypto.randomUUID();store.saveSession(sid,{form:Object.fromEntries(Object.entries(blankRide()).map(([k,v])=>[k,typeof v==='boolean'?v:v===null?'':String(v)])),manual_fields:['tips_paisa','financial_basis']},null,null,0);store.db.prepare("UPDATE settings SET value='\"Europe/London\"' WHERE key='timezone'").run();
  assert.throws(()=>store.saveSession(crypto.randomUUID(),{form:Object.fromEntries(Object.entries(blankRide()).map(([k,v])=>[k,typeof v==='boolean'?v:v===null?'':String(v)])),manual_fields:['unknown_field']},null,null,0));
  const archive=new Backups(store).snapshot();const backups=new Backups(destination);destination.save({...complete(),cash_collected_paisa:10000},'reviewed');const oldId=destination.list()[0]!.id;
  await assert.rejects(()=>backups.stage(altered(archive,m=>m.backup_version=99)));await assert.rejects(()=>backups.stage(altered(archive,m=>{const p=JSON.parse(m.tables.sessions[0].payload);p.manual_fields=['unknown_field'];m.tables.sessions[0].payload=JSON.stringify(p);}))); await assert.rejects(()=>backups.stage(altered(archive,(_,files)=>{delete files[`originals/${(uploaded.attachment as any).storage_key}`];})));await assert.rejects(()=>backups.stage(altered(archive,m=>m.tables.attachments[0].hash='0'.repeat(64))));await assert.rejects(()=>backups.stage(altered(archive,m=>m.tables.import_items[0].attachment_id=crypto.randomUUID())));await assert.rejects(()=>backups.stage(Buffer.from(zipSync({'../escape':strToU8('bad')}))));await assert.rejects(()=>backups.stage(archive,step=>{if(step==='staged')throw new Error('injected staging failure');}));assert.equal(destination.get(oldId).status,'reviewed');
  const preview=await backups.stage(archive);assert.equal(preview.counts.rides,3);assert.throws(()=>backups.activate(preview.token,false));
  for(const step of ['before-activation','after-pointer','after-open']){assert.throws(()=>backups.activate(preview.token,true,actual=>{if(actual===step)throw new Error('injected activation failure');}));assert.equal(destination.get(oldId).status,'reviewed');}
  backups.activate(preview.token,true);assert.equal(destination.get(reviewed.id).cash_collected_paisa,50000);assert.throws(()=>destination.get(oldId));assert.equal(hash(new Intake(destination).bytes(item.attachment_id)),hash(image));
  for(const table of BACKUP_TABLES)assert.deepEqual(destination.db.prepare(`SELECT * FROM ${table} ORDER BY rowid`).all(),store.db.prepare(`SELECT * FROM ${table} ORDER BY rowid`).all(),table);
  assert.equal(summarize(destination.list()).excluding,41000);assert.equal(summarize(destination.list()).count,1);
  destination.close();destination=new Store(fresh);assert.equal(destination.get(reviewed.id).status,'reviewed');assert.equal(hash(new Intake(destination).bytes(item.attachment_id)),hash(image));
  store.close();store=new Store(root);assert.equal(store.get(reviewed.id).status,'reviewed'); // original generation remains intact.
 }finally{store.close();destination.close();rmSync(root,{recursive:true,force:true});rmSync(fresh,{recursive:true,force:true});}
});
