import { test, expect } from '@playwright/test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store } from '../server/store.ts';
import { createApp } from '../server/app.ts';
let store: Store; let server: ReturnType<typeof createApp>; let directory: string; let base: string;
test.beforeAll(async () => {
  directory = mkdtempSync(join(tmpdir(), 'uber-browser-')); store = new Store(directory); server = createApp(store);
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); base = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
});
test.afterAll(async () => { await new Promise<void>(resolve => server.close(() => resolve())); store.close(); rmSync(directory, { recursive: true, force: true }); });
test('M1 manual entry, recovery, review, correction, trash/restore and CSV', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const external: string[] = []; page.on('request', r => { if (!r.url().startsWith(base)) external.push(r.url()); });
  await page.goto(base); await page.getByRole('button', { name: '+ Add ride' }).click();
  await page.getByLabel('Trip date', { exact: true }).fill('2026-10-06');
  await page.getByLabel('Pickup time', { exact: true }).fill('09:30:00');
  await page.getByLabel('Pickup location', { exact: true }).fill('ঢাকা, Airport');
  await page.getByLabel('Drop location', { exact: true }).fill('Office');
  await page.getByLabel('Financial basis').selectOption('worksheet_cash_plus_credit');
  await page.getByLabel('Cash collected', { exact: true }).fill('500');
  await page.getByLabel('Uber credit', { exact: true }).fill('0');
  await page.getByLabel('Tips included in receipts', { exact: true }).fill('40');
  await page.getByLabel('Uber commission', { exact: true }).fill('50');
  await expect(page.getByRole('button', { name: 'Save reviewed' })).toBeDisabled();
  // Refresh immediately after typing, before debounce; browser recovery retains the edit.
  await page.getByLabel('Per-ride pass charge', { exact: true }).fill('0');
  await page.reload(); await page.getByRole('button', { name: /Resume new ride/ }).click();
  await expect(page.getByLabel('Per-ride pass charge', { exact: true })).toHaveValue('0');
  await expect(page.getByText('BDT 410.00', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.getByText('Draft saved. It is excluded from income totals.')).toBeVisible();
  await expect(page.locator('.stats').getByText('BDT 0.00').first()).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('checkbox', { name: /I reviewed all five/ }).check();
  await page.getByRole('button', { name: 'Save reviewed' }).click();
  await expect(page.getByText('Reviewed ride saved.', { exact: true })).toBeVisible();
  await expect(page.locator('.stats').getByText('BDT 410.00')).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Cash collected', { exact: true }).fill('600');
  await expect(page.getByRole('checkbox', { name: /I reviewed all five/ })).not.toBeChecked();
  await expect(page.getByRole('button', { name: 'Save reviewed' })).toBeDisabled();
  await expect.poll(async () => (await (await page.request.get(base + '/api/rides')).json()).summary.excluding).toBe(41000);
  await page.getByRole('button', { name: 'Keep unfinished & close' }).click();
  await expect(page.locator('.stats').getByText('BDT 410.00')).toBeVisible();
  await page.getByRole('button', { name: /Resume ride edit/ }).click();
  await expect(page.getByLabel('Cash collected', { exact: true })).toHaveValue('600');
  await page.getByRole('checkbox', { name: /I reviewed all five/ }).check();
  await page.getByRole('button', { name: 'Save reviewed' }).click();
  await expect(page.locator('.stats').getByText('BDT 510.00')).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('button', { name: 'View correction history' }).click();
  await expect(page.locator('.history')).toContainText('Cash collected: BDT 500.00 → BDT 600.00');
  await page.getByRole('button', { name: 'Keep unfinished & close' }).click();
  page.on('dialog', d => d.accept());
  await page.getByRole('button', { name: 'Trash', exact: true }).click();
  await expect(page.locator('.stats').getByText('BDT 0.00').first()).toBeVisible();
  await page.getByLabel('Status', { exact: true }).selectOption('deleted');
  await page.getByRole('button', { name: 'Restore', exact: true }).click();
  await page.getByLabel('Status', { exact: true }).selectOption('reviewed');
  await expect(page.locator('.stats').getByText('BDT 510.00')).toBeVisible();
  await page.getByLabel('Month', { exact: true }).fill('2026-10');
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('link', { name: 'Export current selection' }).click();
  const download = await downloadPromise; expect(download.suggestedFilename()).toBe('uber-rides-2026-10.csv');
  const csvResponse = await page.request.get(base + '/api/export?month=2026-10'); expect(await csvResponse.text()).toContain('600.00,0.00,50.00,0.00,40.00');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Ride ledger' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/uber-tracker-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.screenshot({ path: '/tmp/uber-tracker-desktop.png', fullPage: true });
  expect(errors).toEqual([]); expect(external).toEqual([]);
});
