import{test,expect}from'@playwright/test';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import sharp from'sharp';import{Store}from'../server/store.ts';import{createApp}from'../server/app.ts';import{hash,Intake}from'../server/intake.ts';
let directory:string;let store:Store;let server:ReturnType<typeof createApp>;let base:string;let port:number;
async function start(){store=new Store(directory);server=createApp(store);await new Promise<void>(r=>server.listen(port??0,'127.0.0.1',r));port=(server.address()as{port:number}).port;base=`http://127.0.0.1:${port}`;}
test.beforeAll(async()=>{directory=mkdtempSync(join(tmpdir(),'uber-offline-'));await start();});
test.afterAll(async()=>{await new Promise<void>(r=>server.close(()=>r()));store.close();rmSync(directory,{recursive:true,force:true});});
test('M5 installed-build offline import → actual OCR → review → dashboard → CSV → backup/restore → app restart',async({page,context})=>{
 test.setTimeout(120000);const external:string[]=[],requested:string[]=[],errors:string[]=[];
 await context.route('**/*',route=>{const url=route.request().url();requested.push(url);if(!url.startsWith(base)){external.push(url);return route.abort();}return route.continue();});page.on('pageerror',e=>errors.push(e.message));
 const image=await sharp('tests/fixtures/synthetic-trip.svg').png().toBuffer();
 await page.goto(base);await page.getByRole('button',{name:'Import',exact:true}).click();await page.getByLabel('Choose screenshots',{exact:true}).setInputFiles({name:'synthetic-offline-trip.png',mimeType:'image/png',buffer:image});
 await page.getByRole('button',{name:'Recognize / retry'}).click();await expect(page.getByText('complete',{exact:true})).toBeVisible({timeout:90000});await page.getByRole('button',{name:'Review this trip'}).click();await page.getByRole('button',{name:'Apply unambiguous candidates to blank fields'}).click();await expect(page.getByLabel('Cash collected',{exact:true})).toHaveValue('500.00');
 await page.getByLabel('Financial basis').selectOption('worksheet_cash_plus_credit');await page.getByRole('checkbox',{name:/I reviewed all five/}).check();await page.getByRole('button',{name:'Save reviewed',exact:true}).click();await expect(page.getByText('Reviewed ride saved.',{exact:true})).toBeVisible();
 const before=await(await page.request.get(base+'/api/rides')).json();expect(before.summary.excluding).toBe(41000);const id=before.rides[0].id;const source=(await(await page.request.get(base+`/api/rides/${id}/sources`)).json())[0];expect(hash(new Intake(store).bytes(source.attachment_id))).toBe(hash(image));
 await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByLabel('Dashboard month').fill('2026-10');await expect(page.getByText('BDT 410.00',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Rides',exact:true}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Export current selection'}).click();expect((await downloadPromise).suggestedFilename()).toBe('uber-rides-export.csv');const csv=await(await page.request.get(base+'/api/export')).text();expect(csv).toContain(`originals/${source.attachment.storage_key}`);expect(csv).not.toContain(directory);
 const archive=await(await page.request.get(base+'/api/backup')).body();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Trash',exact:true}).click();await expect(page.locator('.stats').getByText('BDT 0.00').first()).toBeVisible();
 await page.getByRole('button',{name:'Settings & backup',exact:true}).click();await page.getByLabel('Backup ZIP',{exact:true}).setInputFiles({name:'offline-backup.zip',mimeType:'application/zip',buffer:archive});await expect(page.getByRole('heading',{name:'Validated restore preview'})).toBeVisible();await page.getByRole('button',{name:'Confirm replacement & restore'}).click();await expect(page.getByRole('heading',{name:'Ride ledger'})).toBeVisible();
 await new Promise<void>(r=>server.close(()=>r()));store.close();await start();await page.goto(base);await expect(page.locator('.stats').getByText('BDT 410.00')).toBeVisible();expect(store.get(id).status).toBe('reviewed');expect(hash(new Intake(store).bytes(source.attachment_id))).toBe(hash(image));expect(store.db.prepare('SELECT count(*) AS count FROM field_observations').get()!.count).toBeGreaterThan(0);
 await page.setViewportSize({width:390,height:844});for(const label of ['Dashboard','Import','Settings & backup','Rides']){await page.getByRole('button',{name:label,exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('.panel').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByRole('button',{name:'Edit',exact:true}).click();await expect(page.getByRole('heading',{name:'Source screenshots'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'/tmp/uber-final-review-mobile.png',fullPage:true});
 expect(requested.some(url=>url.includes('/ocr/worker.min.js'))).toBe(true);expect(requested.some(url=>url.includes('.wasm'))).toBe(true);expect(requested.some(url=>url.includes('eng.traineddata.gz'))).toBe(true);await page.route('**/api/sessions/*',route=>route.request().method()==='PUT'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Injected persistence error'})}):route.continue());
 await page.getByLabel('Cash collected',{exact:true}).fill('620.00');await expect(page.getByText('Autosave failed — edits retained in this browser')).toBeVisible();await expect(page.getByRole('alert').first()).toContainText('Injected persistence error');expect(store.get(id).cash_collected_paisa).toBe(50000);
 await page.reload();await page.getByRole('button',{name:/Resume ride edit/}).click();await expect(page.getByLabel('Cash collected',{exact:true})).toHaveValue('620.00');
 expect(external).toEqual([]);expect(errors).toEqual([]);
});
