import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync,rmSync,readFileSync,readdirSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import sharp from'sharp';import{zipSync,strToU8}from'fflate';import{Store}from'../server/store.ts';import{Intake,hash}from'../server/intake.ts';import{Backups}from'../server/backup.ts';import{createApp}from'../server/app.ts';
test('M5 20 representative-size files persist, batch limit/type rejection and shared hash reuse',async()=>{
 const directory=mkdtempSync(join(tmpdir(),'uber-max-batch-'));let store=new Store(directory);let intake=new Intake(store);
 try{const images:Buffer[]=[];for(let i=0;i<20;i++)images.push(Buffer.concat([await sharp({create:{width:1080,height:1000,channels:3,background:{r:240,g:240,b:240}}}).composite([{input:Buffer.from(`<svg width="1080" height="1000"><text x="50" y="100" font-size="40">Synthetic trip ${i}</text></svg>`)}]).jpeg({quality:90}).toBuffer(),Buffer.alloc(280000)]));const batch=intake.batches(images.map((b,i)=>({name:`synthetic-${i}.jpg`,size:b.length,type:'image/jpeg'})));for(let i=0;i<20;i++)await intake.upload(batch.id,i,images[i]!);assert.equal(intake.groups().length,20);const items=intake.groups().flatMap(g=>g.items);store.close();store=new Store(directory);intake=new Intake(store);assert.equal(intake.groups().length,20);for(const item of items)assert.equal(hash(intake.bytes(item.attachment_id)),item.attachment.hash);assert.throws(()=>intake.batches(images.concat(images[0]!).map((b,i)=>({name:`${i}.jpg`,size:b.length,type:'image/jpeg'}))));const wrong=intake.batches([{name:'wrong.png',size:images[0]!.length,type:'image/png'}]);await assert.rejects(()=>intake.upload(wrong.id,0,images[0]!));}
 finally{store.close();rmSync(directory,{recursive:true,force:true});}
});
test('M5 archive expansion limits, corruption and local API paths preserve active data',async()=>{
 const directory=mkdtempSync(join(tmpdir(),'uber-release-api-'));const store=new Store(directory);const backups=new Backups(store);const server=createApp(store);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address()as{port:number}).port}`;
 try{const dangerous=Buffer.from(zipSync({'data.json':strToU8('{}')}));let central=-1;for(let i=0;i<dangerous.length-4;i++)if(dangerous.readUInt32LE(i)===0x02014b50){central=i;break;}dangerous.writeUInt32LE(600000000,central+24);await assert.rejects(()=>backups.stage(dangerous));const exportBytes=new Uint8Array(await(await fetch(base+'/api/export')).arrayBuffer());assert.deepEqual(Array.from(exportBytes.slice(0,3)),[239,187,191]);
 const corrupt=backups.snapshot();corrupt[40]^=1;await assert.rejects(()=>backups.stage(corrupt));assert.equal((await fetch(base+'/api/restore/preview',{method:'POST',body:'garbage'})).status,400);assert.equal((await fetch(base+'/api/attachments/..%2F..%2Fetc%2Fpasswd/original')).status,400);assert.equal((await fetch(base+'/api/import/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({files:[{name:'bad.gif',size:1,type:'image/gif'}]})})).status,400);assert.equal((await fetch(base+'/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({timezone:'invalid'})})).status,400);assert.equal(store.list().length,0);}
 finally{await new Promise<void>(r=>server.close(()=>r()));store.close();rmSync(directory,{recursive:true,force:true});}
});
