import { useEffect,useRef,useState } from 'react';import {api} from './api.ts';import {blankRide,decimal,formatDuration,type RideInput,type Ride} from './shared/domain.ts';
export type Observation={id:string;field:string;value:string|number;exact_text:string;attachment_id:string;confidence:number;active:boolean;parser_version:string;engine:string;position:unknown};
type View={observations:Observation[];current:Observation[];signature:string;decisions:{field:string;value:unknown;origin:string;explained:string}[]};
export function candidateFormValue(field:string,value:unknown):string{return field.endsWith('_paisa')?decimal(value as number):field==='distance_meters'?decimal(value as number,3):field==='duration_seconds'?formatDuration(value as number):String(value);}
export function EvidenceReview({id,input,pick,onAttached,onApplying,onSuggestions,refreshKey}:{id:string|null;input:RideInput|null;pick:(key:keyof RideInput,value:string)=>void;onAttached:(r:Ride)=>void;onApplying?:(busy:boolean)=>void;onSuggestions:(observations:Observation[])=>void;refreshKey:number}){
 const [view,setView]=useState<View|null>(null);const [matches,setMatches]=useState<{ride:Ride;reason:string}[]>([]);const [error,setError]=useState('');const [reason,setReason]=useState('');const [notice,setNotice]=useState('');const [tripId,setTripId]=useState('');
 const suggestions=useRef(onSuggestions);suggestions.current=onSuggestions;
 async function load(){if(id)setView(await api<View>(`/api/rides/${id}/evidence`));}
 useEffect(()=>{let alive=true;if(id)void api<View>(`/api/rides/${id}/evidence`).then(v=>{if(alive){setView(v);if(refreshKey>0)suggestions.current(v.current.filter(o=>!v.decisions.some(d=>d.field===o.field&&d.origin==='manual'&&d.value===null)));}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[id,refreshKey]);
 useEffect(()=>{let alive=true;if(id&&input)api<{candidates:{ride:Ride;reason:string}[]}>(`/api/rides/${id}/duplicates`,'POST',{input}).then(d=>{if(alive)setMatches(d.candidates);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[id,JSON.stringify(input)]);
 if(!id)return null;
 async function use(o:Observation){try{setError('');if(o.field==='trip_id')setTripId(String(o.value));else pick(o.field as keyof RideInput,candidateFormValue(o.field,o.value));await api(`/api/rides/${id}/resolve`,'POST',{field:o.field,value:o.value,observation_id:o.id,reason:'Selected after comparing the source screenshot'});await load();}catch(e){setError((e as Error).message);}}
 async function resolve(field:string){try{setError('');await api(`/api/rides/${id}/resolve`,'POST',{field,value:field==='trip_id'?tripId:input?.[field as keyof RideInput],observation_id:null,reason});await load();setNotice('Current correction recorded. Financial changes still require confirmation.');}catch(e){setError((e as Error).message);}}
 const fields=[...new Set(view?.current.map(o=>o.field)??[])];
 return <section className="evidence-review"><h3>Field evidence · experimental parser</h3><p>Compare candidates with the original. OCR confidence does not confirm financial meaning. Applying candidates fills blank fields only; it preserves your manual corrections.</p>{error&&<p role="alert" className="error-text">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {!!fields.length&&<button type="button" className="secondary" onClick={async()=>{onApplying?.(true);try{for(const field of fields){const options=view!.current.filter(o=>o.field===field);const distinct=new Set(options.map(o=>JSON.stringify(o.value)));const current=input?.[field as keyof RideInput];if(distinct.size===1&&(current===null||current===''||current==='Unknown'||field==='financial_basis'&&current==='unresolved'))await use(options[0]!);}}finally{onApplying?.(false);}}}>Apply unambiguous candidates to blank fields</button>}
  <details><summary>Current field origins</summary>{Object.keys(blankRide()).filter(k=>!['financial_confirmed','adjustment_reason'].includes(k)).map(k=>{const v=input?.[k as keyof RideInput];const decision=view?.decisions.find(d=>d.field===k);const observed=view?.current.some(o=>o.field===k);const matches=view?.current.some(o=>o.field===k&&JSON.stringify(o.value)===JSON.stringify(v));const origin=v===null||v===''||v===undefined?'missing':decision&&JSON.stringify(decision.value)===JSON.stringify(v)?decision.origin:matches?'extracted':observed?'corrected':'manual';return <p key={k}>{k.replaceAll('_',' ')}: {origin}</p>;})}</details>
  <label>Explanation for a correction or separate ride<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="What did you verify?"/></label>
  {fields.map(field=>{const observations=view!.current.filter(o=>o.field===field);const distinct=new Set(observations.map(o=>JSON.stringify(o.value)));const current=input?.[field as keyof RideInput];const decision=view!.decisions.find(d=>d.field===field);const origin=current===null||current===''?'missing':decision&&JSON.stringify(decision.value)===JSON.stringify(current)?decision.origin:observations.some(o=>JSON.stringify(o.value)===JSON.stringify(current))?'extracted':observations.length?'corrected':'manual';return <details key={field} open={distinct.size>1}><summary>{field.replaceAll('_',' ')} · {origin}{distinct.size>1?' · conflicting observations':''}</summary>{observations.map(o=><article key={o.id}><strong>{candidateFormValue(field,o.value)}</strong><pre>{o.exact_text}</pre><small>Image {o.attachment_id.slice(0,8)} · confidence {o.confidence.toFixed(1)}% · {o.engine} · parser {o.parser_version}</small><button type="button" className="text-button" onClick={()=>void use(o)}>Use this candidate</button></article>)}{distinct.size>1&&<button type="button" className="secondary" onClick={()=>void resolve(field)}>Resolve using my current correction</button>}</details>;})}
  <label>Optional screenshot trip ID<input value={tripId} onChange={e=>setTripId(e.target.value)}/></label><button type="button" className="text-button" onClick={()=>void resolve('trip_id')}>Record trip ID</button>
  {!!matches.length&&<div className="review-notes"><h3>Possible duplicate trips</h3><p>The incoming draft is excluded from totals. Compare before deciding.</p>{matches.map(m=><article key={m.ride.id}><strong>{m.ride.trip_date} {m.ride.pickup_time}</strong><p>{m.ride.pickup_location??'Unknown'} → {m.ride.drop_location??'Unknown'} · {m.reason}</p><button type="button" className="secondary" onClick={async()=>{if(!confirm('Attach incoming screenshots to this existing ride and move the incoming draft to trash, preserving its history? Existing financial values will remain.'))return;try{onAttached(await api<Ride>(`/api/rides/${id}/attach`,'POST',{target_id:m.ride.id,confirmed:true}));}catch(e){setError((e as Error).message);}}}>Attach to existing ride</button></article>)}<button type="button" className="secondary" onClick={async()=>{try{await api(`/api/rides/${id}/separate`,'POST',{input,reason});setNotice('Separate-ride reason saved. Confirm finances, then Save reviewed.');}catch(e){setError((e as Error).message);}}}>Save separately with this explanation</button><p>To skip this incoming trip, close the draft and move it to trash.</p></div>}
  {view?.observations.some(o=>!o.active)&&<details><summary>Previous extraction evidence</summary>{view.observations.filter(o=>!o.active).map(o=><p key={o.id}>{o.field}: {candidateFormValue(o.field,o.value)} · {o.exact_text}</p>)}</details>}
 </section>;
}
