import{useEffect,useState}from'react';import{api}from'./api.ts';
export function Settings(){const[data,setData]=useState<any>(null);const[timezone,setTimezone]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[preview,setPreview]=useState<any>(null);const[busy,setBusy]=useState(false);
 useEffect(()=>{api<any>('/api/settings').then(d=>{setData(d);setTimezone(d.timezone);}).catch(e=>setError(e.message));},[]);
 async function upload(file:File){setBusy(true);setError('');setPreview(null);try{const response=await fetch('/api/restore/preview',{method:'POST',body:file});const result=await response.json();if(!response.ok)throw new Error(result.error);setPreview(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Settings & backup</h2>{error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<h3>Storage</h3><p className="storage-path">{data?.data_directory}</p><p>User data stays outside the application. Upgrades preserve the configured data root. Previous restored generations remain on disk for recovery.</p><label>Default timezone for new rides<input disabled={busy||!data} value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><button className="secondary" disabled={busy||!data} onClick={async()=>{try{await api('/api/settings','PUT',{timezone});setNotice('Default timezone saved. Existing local trip dates are unchanged.');}catch(e){setError((e as Error).message);}}}>Save timezone</button>
 <h3>Local OCR</h3><p>{data?.ocr.available?'English OCR assets are installed locally.':'OCR assets unavailable: run npm run setup:ocr and rebuild.'}</p><p className="muted">{data?.ocr.manifest?.engine} · {data?.ocr.manifest?.language} · core {data?.ocr.manifest?.core}</p>
 <h3>Complete backup</h3><p>ZIP includes reviewed rides, drafts, trash, original screenshots, OCR and evidence, corrections, unfinished sessions, and settings. CSV is a ledger export, not a complete backup.</p><a className="button" href="/api/backup">Download full backup ZIP</a>
 <h3>Restore a backup</h3><p>Choose a ZIP to validate and preview it. Restoration replaces the active dataset after your confirmation. Maximum ZIP size: 200 MB; maximum expanded size: 512 MB. Keep your current backup before replacing data.</p><label>Backup ZIP<input type="file" accept=".zip,application/zip" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>{busy&&<p role="status">Validating archive and original images…</p>}
 {preview&&<div className="review-notes"><h3>Validated restore preview</h3><p>{preview.counts.rides} rides · {preview.counts.attachments} originals · {preview.counts.sessions} unfinished sessions · {preview.counts.history} history events · {preview.counts.ocr_runs} OCR runs · {preview.counts.field_observations} observations</p><p>Preview expires at {new Date(preview.expires_at).toLocaleString()}.</p><button disabled={busy} onClick={async()=>{if(!confirm(`Replace all active data with this validated backup (${preview.counts.rides} rides and ${preview.counts.attachments} originals)?`))return;setBusy(true);try{await api('/api/restore/activate','POST',{token:preview.token,confirmed:true});localStorage.removeItem('uber-tracker-pending-v1');location.reload();}catch(e){setError((e as Error).message);setBusy(false);}}}>Confirm replacement & restore</button></div>}
 <h3>Calculation and recovery</h3><p>Excluding tips = cash + credit − commission − per-ride pass − tips. Receipts must include tips and precede the deductions. Already-net-only records remain drafts. Negative/unusual adjustments require explanation.</p><p>Unfinished sessions appear in Rides after refresh. Retry failed/cancelled OCR from Import. Trash supports restoration; permanent removal requires confirmation. If recovery is needed after restoring, stop the app and consult the README’s retained-generation instructions.</p>
 </section>;
}
